camera_matrix:
  cols: '3'
  data: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 3
      - 3
    - !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      HGrvXT1Eg0AAAAAAAAAAACEbjkYL03VAAAAAAAAAAABJPWLFn/6CQDOaCzVoRW5AAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAPA/
  dt: d
  rows: '3'
